module.exports = {
    secret: 'This is a secret',
    db_dialect: 'mariadb',
    db_host: '192.168.0.168',
    db_port: '3306',
    db_name: 'aura2020',
    db_user: 'aurauser',
    db_pass: '24e4464dmysql',
    pw_salt: 'This is namak',
    MID: 'wkwuSC67220918333714',
    PAYTM_ENVIRONMENT: 'TEST',
    PAYTM_MERCHANT_KEY: 'g#DBkf__tJrxXRI!',
    WEBSITE: 'WEBSTAGING',
    CHANNEL_ID: 'WEB',
    INDUSTRY_TYPE_ID: 'Retail',
    CALLBACK_URL: 'http://localhost:3000/response',
    PAYTM_TEST_URL: 'https://securegw-stage.paytm.in/order/process',
    PAYTM_PROD_URL: '',
};
